language: objective-c
osx_image: xcode12.2
script:
- xcodebuild -workspace ILPDFKitTests/ILPDFKitTests.xcworkspace -scheme ILPDFKitTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' test
- xcodebuild -workspace ILPDFKitExample/ILPDFKitExample.xcworkspace -scheme ILPDFKitExample -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' test
